### ISSUE TITLE
fatal error: all goroutines are asleep - deadlock!

### ISSUE THREAD

**Issue by pdiakumis** [brentp/excord#1]
Brent,

Trying to use excord with stix. Running Ryan Layer’s [example stix script](https://github.com/ryanlayer/stix/blob/master/README.md)  on our cluster fails with the following - any idea what’s going on? I've tried both excord released versions.

Many thanks - Peter

```
spartan $ cat run_excord.sh
#!/usr/bin/env bash
#SBATCH -n 1
#SBATCH --mem=20000
#SBATCH --time=1:00:00
#SBATCH -o log.excord%j.out
#SBATCH -e log.excord%j.err

set -euo pipefail

#wget -O excord https://github.com/brentp/excord/releases/download/v0.2.2/excord_linux64
#chmod +x excord

in_dir="../../data/nogit/stix"
out_dir="${in_dir}/four_alt"

for sample in HG00672.13.14 HG00674.13.14 NA12812.13.14 NA12878.13.14; do
    samtools view ${in_dir}/${sample}.bam \
        | ~/my_apps/excord \
            --discordantdistance 500 \
            --fasta ${in_dir}/hs37d5.fa.gz \
            /dev/stdin \
        | LC_all=C sort --buffer-size 2G -k1,1 -k2,2n -k3,3n \
        | bgzip -c > ${out_dir}/${sample}.bed.gz
done

spartan $ cat log.excord1421375.err
2017/11/17 16:59:06  /dev/stdin
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc42001c69c)
	/home/brentp/go/go1.9/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0xc42001c690)
	/home/brentp/go/go1.9/src/sync/waitgroup.go:131 +0x72
main.(*excord).Close(0xc420082180, 0x1f4, 0xc42004f900)
	/home/brentp/go/src/github.com/brentp/excord/cmd/excord/excord.go:287 +0xc6
panic(0x65b8e0, 0xc4200583f0)
	/home/brentp/go/go1.9/src/runtime/panic.go:491 +0x283
main.pcheck(0x7dc6a0, 0xc4200583f0)
	/home/brentp/go/src/github.com/brentp/excord/cmd/excord/excord.go:323 +0x4a
main.stdinMain(0xc42000e1e0, 0x0)
	/home/brentp/go/src/github.com/brentp/excord/cmd/excord/excord.go:650 +0x298
main.main()
	/home/brentp/go/src/github.com/brentp/excord/cmd/excord/excord.go:680 +0x1099

goroutine 5 [chan receive]:
main.newExcord.func1(0xc420082180)
	/home/brentp/go/src/github.com/brentp/excord/cmd/excord/excord.go:180 +0x81
created by main.newExcord
	/home/brentp/go/src/github.com/brentp/excord/cmd/excord/excord.go:179 +0x1e1

spartan $ ~/my_apps/excord --version
excord 0.2.3
```

**Comment by brentp** [comment]
can you try running with samtools view -b ? excord expects bam input.

you can also run as `GOMAXPROCS=1 ~/my_apps/excord`, that should get you past this error.

and is it possible that you could share a small bam that has this problem so I can debug further?

**Comment by pdiakumis** [comment]
Brent, thanks for that, fantastic, just needed that `-b` flag for BAM input, looks to be running ok now with it (running interactive session on cluster) - I might update Ryan's given example too. The BAM file(s) I used are taken from those links in that stix README I linked above in case you were wondering.

```
spartan-bm032 $ samtools view ../../data/nogit/stix/HG00672.13.14.bam | ~/my_apps/excord --discordantdistance 500 --fasta ../../data/nogit/stix/hs37d5.fa.gz /dev/stdin | LC_all=C sort --buffer-size 2G -k1,1 -k2,2n -k3,3n | bgzip -c > ../../data/nogit/stix/four_alt/tmp.bed.gz
2017/11/18 10:42:51  /dev/stdin
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc42001872c)
	/home/brentp/go/go1.9/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0xc420018720)
	/home/brentp/go/go1.9/src/sync/waitgroup.go:131 +0x72
main.(*excord).Close(0xc420082180, 0x1f4, 0xc420043900)
	/home/brentp/go/src/github.com/brentp/excord/cmd/excord/excord.go:288 +0xc6
panic(0x65b8e0, 0xc42005a3f0)
	/home/brentp/go/go1.9/src/runtime/panic.go:491 +0x283
main.pcheck(0x7dc6a0, 0xc42005a3f0)
	/home/brentp/go/src/github.com/brentp/excord/cmd/excord/excord.go:324 +0x4a
main.stdinMain(0xc42000e1e0, 0x0)
	/home/brentp/go/src/github.com/brentp/excord/cmd/excord/excord.go:651 +0x298
main.main()
	/home/brentp/go/src/github.com/brentp/excord/cmd/excord/excord.go:681 +0x10ab

goroutine 5 [chan receive]:
main.newExcord.func1(0xc420082180)
	/home/brentp/go/src/github.com/brentp/excord/cmd/excord/excord.go:181 +0x81
created by main.newExcord
	/home/brentp/go/src/github.com/brentp/excord/cmd/excord/excord.go:180 +0x1e1


spartan-bm032 $ samtools view -b ../../data/nogit/stix/HG00672.13.14.bam | ~/my_apps/excord --discordantdistance 500 --fasta ../../data/nogit/stix/hs37d5.fa.gz /dev/stdin | LC_all=C sort --buffer-size 2G -k1,1 -k2,2n -k3,3n | bgzip -c > ../../data/nogit/stix/four_alt/tmp.bed.gz
2017/11/18 10:43:07  /dev/stdin
spartan-bm032 $ gunzip -c ../../data/nogit/stix/four_alt/tmp.bed.gz | head
1	33722	33722	1	14	101671675	101671766	-1	0
1	73805	73805	1	13	77197794	77197885	1	0
1	235169	235169	-1	14	66010703	66010794	-1	0
1	567537	567537	1	14	72472274	72472365	1	0
1	567910	567910	-1	14	51248148	51248239	1	0
1	567977	567977	-1	14	75739119	75739210	-1	0
1	603195	603195	-1	13	33762727	33762818	-1	0
1	637550	637550	-1	13	50408283	50408374	-1	0
1	746239	746239	1	13	94080369	94080458	-1	0
1	815411	815411	-1	13	75437321	75437412	1	0
```
